api_platform:
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/json' ]
    swagger:
        versions: [ 3 ]

    exception_to_status:
        App\Exception\UserNotOwnedException: 403

    title: 'BileMo'
    description: 'Business To Business API. You need to have a confirmed account to use this API, if you want to do business with us, contact us at admin@bilemo.com'

    version: '1.0.0'
    show_webby: false

    defaults:
        pagination_items_per_page: 10

        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]